"""First migration

Revision ID: 522497b6f61d
Revises: a4c58a0bb128
Create Date: 2024-02-20 00:38:09.552464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522497b6f61d'
down_revision = 'a4c58a0bb128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
