"""First migration

Revision ID: 93e6e85e4149
Revises: b38cd3398943
Create Date: 2024-02-20 13:49:35.644214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e6e85e4149'
down_revision = 'b38cd3398943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
