"""First migration

Revision ID: b38cd3398943
Revises: 522497b6f61d
Create Date: 2024-02-20 00:40:25.044486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38cd3398943'
down_revision = '522497b6f61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
